### ISSUE TITLE
Drawer scrolls window and large padding area displayed above drawer footer on Safari 

### ISSUE THREAD

**Issue by jeffvg** [pxblue/doc-it#149] opened 2020-04-03 18:45 UTC
#### Describe the bug
Drawer and page scrolling behavior observed: If a several parent directories are expanded and scrolling down the drawer causes window to scroll.
Empty space between release notes div and drawer footer when all directories are collapsed. 

#### What is the expected behavior?
If focus is on drawer the window should not scroll and empty space not to exists

#### What are the steps to reproduce?
1. Go to https://pxblue.github.io/
2. Open drawer and expand several parent menu items or click on getting started and expand parent menu items.
3. While hovering in drawer area, scroll
4. Window/page scrolling with drawer

#### Screenshots or links to minimum reproduction example
<img width="422" alt="safari-drawer" src="https://user-images.githubusercontent.com/37150565/78394335-7759e100-75b9-11ea-8d21-5e72c3210e37.png">

#### What is your environment?

 Framework
- [ ] Angular
- [X] React
- [ ] Ionic
- [ ] React Native

 Browser
- [ ] Internet Explorer
- [ ] Edge
- [X] Safari
- [ ] Chrome
- [ ] Firefox

 Operating System
- [X] MacOS
- [ ] Windows
- [X] Other
		
#### Anything else to add?
Behavior is only noticed in Safari desktop and iPad

**Comment by huayunh** [comment] 2020-04-03 21:48
This is not reproducible on my mac + safari (even after I changed the user agent from default to safari iPad iOS 13). However, I noticed this weird scrollbar behavior: 

![image](https://user-images.githubusercontent.com/8997218/78407483-f1e32a80-75d2-11ea-8ff2-5c1e76a40bcc.png)

It looks like a z index issue.

**Comment by andrupu** [comment] 2020-04-22 15:02
@jeffvg this is not an issue.
@huayunh please log your z-index issue separate from this issue and close this bug.

**Closed** 2020-06-23 16:36 UTC
Labels: bug, safari
